excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://BraveHeart91.github.io
title: BraveHeart91
tagline: A log of everyday life 
description: Couple moments from my daily life..
paginate: 5